# Generated by Django 4.0.6 on 2022-09-26 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TimeRules', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='create',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ListingDate', models.CharField(max_length=50)),
                ('writting', models.CharField(max_length=50)),
                ('collage', models.CharField(max_length=50)),
            ],
        ),
        migrations.DeleteModel(
            name='Items',
        ),
    ]
