# Generated by Django 4.0.6 on 2022-09-26 14:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TimeRules', '0002_create_delete_items'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='create',
            new_name='Creates',
        ),
    ]
