# Generated by Django 4.0.6 on 2022-09-28 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TimeRules', '0003_rename_create_creates'),
    ]

    operations = [
        migrations.CreateModel(
            name='timestamps',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serialNumber', models.CharField(max_length=50)),
                ('title', models.CharField(max_length=50)),
                ('fromTime', models.CharField(max_length=50)),
                ('toTime', models.CharField(max_length=50)),
                ('collage', models.CharField(max_length=50)),
                ('writting', models.CharField(max_length=50)),
            ],
        ),
    ]
