# Generated by Django 4.0.6 on 2022-09-29 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TimeRules', '0004_timestamps'),
    ]

    operations = [
        migrations.AddField(
            model_name='timestamps',
            name='minutes',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
