# Generated by Django 4.0.6 on 2022-10-04 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TimeRules', '0005_timestamps_minutes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timestamps',
            name='serialNumber',
            field=models.IntegerField(),
        ),
    ]
